name: Ponzi Auditor Scan
on:
  schedule:
    - cron: '0 12 * * 1-5'  # Weekdays at noon UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python scam_scanner.py > results.txt
      - uses: actions/upload-artifact@v4  # CERTIFIED WORKING VERSION
        with:
          name: audit-results
          path: results.txt